examples/isomorphic/server/src/server.rs
Fix error using Chrome that tries to load `favicon.ico`
=> Return 404 Not Found on missing files

examples/isomorphic/server/src/server.rs
Prevents the sending of trailing zeros,
so the browser isn't showing a 1.9MB download
=> Only send bytes necessary

.travis.yml, Dockerfile, virtual-dom-rs/src/html_macro.rs
@qm3ster this just only adds `events` if we're on wasm32 otherwise it ignores
=> Fix closures on non wasm32 targets

book/src/virtual-dom/html-macro.md, crates/virtual-dom-rs/Cargo.toml, crates/virtual-dom-rs/src/diff.rs, crates/virtual-dom-rs/src/html_macro.rs, crates/virtual-dom-rs/src/lib.rs, crates/virtual-dom-rs/src/patch.rs, crates/virtual-dom-rs/src/virtual_node/browser_events.rs, crates/virtual-dom-rs/src/virtual_node/mod.rs, crates/virtual-dom-rs/tests/create_element.rs, crates/virtual-dom-rs/tests/events.rs
This PR adds support and example usage for the `oninput` event
Closes #41 
---
We'll need to add in more events over time - but I figured step 1 would be PRing an example so that anyone can start contributing more events.
=> Add `BrowserEvents` struct enabling better event support

README.md, book/src/router/README.md, book/src/views/server-side-rendering/how-to-ssr.md, crates/virtual-dom-rs/Cargo.toml, crates/virtual-dom-rs/src/html_macro.rs, crates/virtual-dom-rs/tests/create_element.rs, crates/virtual-dom-rs/tests/events.rs, crates/virtual-node/Cargo.toml, crates/virtual-node/src/lib.rs, examples/isomorphic/app/src/views/home_view.rs, examples/isomorphic/app/src/views/nav_bar_view/nav_bar_item_view.rs
Followup to Issue #44.
A quick guide to changes:
* Added "Event" feature to *web-sys* dependencies for *virtual-dom-rs* and and *virtual-node*.
* Modified `CustomEvents` and the `html!` macro to accept `FnMut(Event) -> ()`.
* Copy/pasted the *oninput* test, but this time using the generic handler syntax.
* Changed all the examples I could find to accept an event object (named `_ev`, usually). I may have missed some.
I didn't touch the versions, though this is a breaking change. I dunno how you handle that.
Something I didn't anticipate: even without casting the `Event` to something more specific, this gives the handler immediate access to the element it's tied to, which is a pretty big win by itself.
=> Pass event object to custom event handlers

examples/isomorphic/client/build-wasm.sh, examples/isomorphic/client/build-wasm.watch.sh
Hello, I tried to run the ismorphic example, but got lots of errors because the `dist` folder doesn't exist on dev run.
```
Listening on port 7878
thread 'arbiter:bfda721a-75c6-485c-8358-33a5d640faa7:actix-net-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
...
```
So this edit just creates it on dev build, it's not the best option, feel free to close and tell me if you have something else in mind.
=> Always create dist folder in iso example

crates/virtual-node/src/lib.rs
This is easier to read than when using the alternate debug format.
=> Make debug format of VirtualNode more compact

crates/virtual-node/src/lib.rs
Instead of `Element(Element(<span>, ...))` it's now `Node::Element(<span>, ...)`. Easier to read and debug.
=> Improve debug representation of VirtualNode

crates/virtual-dom-rs/Cargo.toml, crates/virtual-dom-rs/src/patch/apply_patches.rs, crates/virtual-dom-rs/tests/diff_patch.rs
Right now we get a panic if a text node is to be replaced with an element, because text nodes don't handle the `Replace` patch.
Here's a failing test (don't merge yet), fix will follow.
=> Fix replacing of text nodes

crates/virtual-node/src/lib.rs
This way strings can be moved instead of copied if possible.
=> Accept S: Into<String> as param in VirtualNode::text

.circleci/config.yml, crates/html-macro-test/src/lib.rs, crates/virtual-dom-rs/src/diff/mod.rs, crates/virtual-dom-rs/src/dom_updater.rs, crates/virtual-dom-rs/src/patch/apply_patches.rs, crates/virtual-dom-rs/src/patch/mod.rs, crates/virtual-dom-rs/tests/closures.rs, crates/virtual-dom-rs/tests/create_element.rs, crates/virtual-dom-rs/tests/diff_patch_test_case/mod.rs, crates/virtual-dom-rs/tests/dom_updater.rs, crates/virtual-dom-rs/tests/events.rs, crates/virtual-node/src/lib.rs, crates/virtual-node/src/virtual_node_test_utils.rs
Fixes #70
We weren't holding on to the closures that were created for DOM nodes in the AppendChildren / Replace patches so they just wouldn't work as soon as your VirtualNode got dropped.
=> Store closures for newly appended/replaced nodes

README.md, crates/html-macro/src/parser.rs
Fixes warning that import of `Cell` is unused and compilation failed due to use of undeclared type or module `Rc`. 
Using `rustc 1.34.0-nightly (146aa60f3 2019-02-18)` and the dependencies listed in the readme.
=> Fix readme example and missing Rc import

crates/html-macro-test/src/lib.rs, crates/html-macro/src/parser.rs, crates/virtual-dom-rs/src/diff/mod.rs, crates/virtual-dom-rs/tests/closures.rs, crates/virtual-dom-rs/tests/create_element.rs, crates/virtual-node/src/lib.rs, crates/virtual-node/src/virtual_node_test_utils.rs
While reading source code of virtual_dom_rs, I was confused by VElement's `props`. [the term "properties" and "attributes" has slightly different meanings in DOM](https://stackoverflow.com/a/6004028). VElement's one named `props` but what it contains is "attributes" rather than "properties" I think.
Fixes #77
=> Rename props with attrs

crates/router-rs/src/route.rs, crates/router-rs/src/router.rs
This is a fun one. Perplexingly, the router was handing me the same route for routes that were different.
I can't vouch for the correctness of this routing code, that would take many more comprehensive tests, but it works much better now.
=> Fix router-rs for path segments on the same level

.circleci/config.yml, README.md, book/src/contributing/internal-design/sibling-text-nodes.md, book/src/html-macro/html-macro.md, crates/html-macro-test/src/lib.rs, crates/html-macro/README.md, crates/html-macro/src/lib.rs, crates/html-macro/src/parser.rs, crates/html-macro/src/tag.rs, crates/router-rs-macro-test/src/book_example.rs, crates/router-rs/CHANGELOG.md, crates/router-rs/src/provided.rs, crates/router-rs/src/route.rs, crates/router-rs/src/router.rs, crates/virtual-dom-rs/CHANGELOG.md, crates/virtual-dom-rs/Cargo.toml, crates/virtual-dom-rs/src/dom_updater.rs, crates/virtual-dom-rs/src/lib.rs, crates/virtual-dom-rs/src/patch/apply_patches.rs, crates/virtual-node/Cargo.toml, crates/virtual-node/src/lib.rs, examples/isomorphic/app/src/lib.rs, examples/isomorphic/app/src/views/home_view.rs, examples/isomorphic/app/src/views/nav_bar_view/mod.rs, examples/isomorphic/app/src/views/nav_bar_view/nav_bar_item_view.rs
This PR makes it much easier to interpolate text variables into your HTML.
```rust
let my_text = "hello world";
html! { <div> { text!(my_text) } </div> }
```
```rust
let my_text = "hello world";
html! { <div> { my_text } </div> }
```
Needing a macro for such a common thing was a poor experience
=> Interpolate text into html! macro, remove text! macro

.circleci/config.yml, README.md, book/src/SUMMARY.md, book/src/html-macro/text/README.md, crates/html-macro-test/src/lib.rs, crates/html-macro-test/src/text.rs, crates/html-macro-ui/test.rs, crates/html-macro/src/lib.rs, crates/html-macro/src/parser/braced.rs, crates/html-macro/src/parser/close_tag.rs, crates/html-macro/src/parser/mod.rs, crates/html-macro/src/parser/open_tag.rs, crates/html-macro/src/parser/text.rs, crates/html-macro/src/tag.rs, crates/router-rs-macro-test/src/book_example.rs, crates/virtual-dom-rs/CHANGELOG.md, crates/virtual-dom-rs/Cargo.toml, examples/unit-testing-components/src/main.rs
Fixes #83 
Also refactors a good chunk of the `html-macro` to make it easier to read and a good bit more DRY
=> Preserve spacing around text nodes and braces

crates/html-validation/src/lib.rs, crates/html-validation/src/self_closing.rs, crates/html-validation/src/svg_namespace.rs, crates/virtual-dom-rs/tests/create_element.rs, crates/virtual-node/src/lib.rs, examples/isomorphic/app/src/views/home_view.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chinedufn/percy/104)
=> Add support for inline SVG element

examples/isomorphic/app/Cargo.toml, examples/isomorphic/app/src/lib.rs, examples/isomorphic/app/src/state/mod.rs, examples/isomorphic/app/src/state/msg.rs, examples/isomorphic/app/src/store.rs, examples/isomorphic/app/src/views/contributors_view.rs, examples/isomorphic/app/src/views/home_view.rs, examples/isomorphic/app/src/views/nav_bar_view/mod.rs, examples/isomorphic/app/src/views/nav_bar_view/nav_bar_item_view.rs, examples/isomorphic/client/build-wasm.prod.sh, examples/isomorphic/client/build-wasm.sh, examples/isomorphic/client/src/lib.rs, examples/isomorphic/server/src/index.html, examples/isomorphic/server/src/lib.rs, examples/isomorphic/server/src/main.rs, examples/isomorphic/server/src/server.rs
This pull request is to add the feature to download JSON from the Github API for the isomorphic example.
The JSON data holds information about the contributors for the master branch of Percy.
Right now only the client performs the fetch request, but I'd imagine there's a way to have the server perform the same operation before serving the route.  I'm just not completely sure how to go about doing that.
The contributors are stored in an `Option<Vec<Contributor>>` field for `State`.  While `Contributor` holds the login name and html url for each contributor.  Right now the definition for `Contributor` lives in `app/src/state.rs`.
=> Download example

examples/isomorphic/server/src/index.html
When hard-refreshing against a non-root route in the isomorphic example, the client WASM file's retrieval is attempted relative to the current route rather than the root.
`companies/static/client_bg.wasm` should be `static/client_bg.wasm`, which this PR addresses.
=> Get client wasm file relative to base route rather than current route

book/src/SUMMARY.md, book/src/html-macro/conditional-rendering/README.md, crates/html-macro-test/src/lib.rs, crates/html-macro/src/parser/braced.rs, crates/html-macro/src/parser/mod.rs, crates/html-macro/src/parser/statement.rs
This PR adds single branch if statement capabilities into the html! macro, which is a very common use case in React-like frameworks (generally achieved with `condition && <jsx/>`. See an example below:
```rust
html! {
<div>
<h1>A component</h1>
{if some_condition_is_true {
html! { <span>Child</span> }
}}
</div>
}
```
Currently to do this sort of thing is quite clunky, as if statements are expressions in rust you have to do something like the following which really bloats the components.
```rust
let child = if some_condition_is_true {
html! { <span>Child</span> }
} else {
html! { "" }
};
html! {
<div>
<h1>A component</h1>
{child}
</div>
}
```
I appreciate this is slightly against the grain of rust as you can't do this in traditional rust code however I think it makes sense to include this …
=> Single branch if statement in html! macro

book/src/SUMMARY.md, book/src/html-macro/custom-components/README.md, crates/html-macro-test/src/tests/all_tests.rs, crates/html-macro/src/parser/mod.rs, crates/html-macro/src/parser/open_tag.rs, crates/html-macro/src/tag.rs, crates/html-validation/src/lib.rs, crates/html-validation/src/valid_tags.rs
I've implemented custom components in Percy, similar to what you see in React, so users can use a `<MyComponent/>` pattern rather than `{my_component()}` which feels a bit more up to date with competitor frameworks.
I've had to implement a list of valid html tags to do this (I took them from [here](https://react-cn.github.io/react/docs/tags-and-attributes.html)).
If this isn't the best way of going around this please let me know, or if this is an unwanted change then that's fine too.
I tried to implement children in the same way React handles them, ie a children prop gets added into the child component but I've been round in circles with this - I kept hitting borrowing problems. I also had a look how Yew does it (which is similar to React) and still couldn't figure out a nice way of doing …
=> Custom Components

crates/html-macro/src/parser/mod.rs, crates/virtual-node/src/lib.rs
For convenience.
Also, in html macro, add parenthesis around statements before calling `.into()` so that we can use references.
I'm a bit lazy and I don't want to `.map(|v| v.render).collect()` my views myself 😄
=> IterableNodes: add From<&[View]>, From<&Vec<View>>, and From<Vec<View>>

crates/percy-dom/src/diff.rs, crates/percy-dom/src/patch.rs, crates/percy-dom/src/patch/apply_patches.rs, crates/percy-dom/tests/events.rs, crates/virtual-node/src/event/events_by_node_idx.rs
When old nodes are removed/added, the events ID on nodes that come after
those nodes in the tree need to be updated.
This commit implements this, so that nodes get their events ID updated
as they move around the tree.
=> Fix setting events ID

crates/html-macro-test/src/tests/all_tests.rs, crates/html-macro/src/tag.rs
Similar to #131, this adds support for `as` attributes in html tags, since `as` is a keyword in Rust. [`as` is used in prefetch/preload link tags](https://3perf.com/blog/link-rels/).
Thanks!
=> Support the as attribute in link tags.

crates/html-macro-test/src/tests/ui/invalid_html_tag.rs, crates/html-macro-test/src/tests/ui/invalid_html_tag.stderr, crates/html-macro-test/src/tests/ui/on_create_element_without_key.rs, crates/html-macro-test/src/tests/ui/on_create_element_without_key.stderr, crates/html-macro-test/src/tests/ui/on_remove_element_without_key.rs, crates/html-macro-test/src/tests/ui/on_remove_element_without_key.stderr, crates/percy-dom/Cargo.toml, crates/percy-dom/src/lib.rs, crates/percy-dom/src/render.rs, crates/percy-router/Cargo.toml
This commit adds a function to percy-dom that can be used to create a
request-animation-frame throttled renderer.
This is helpful for powering experiences where you want to rerender
an application everytime application state changes.
=> Add render fn to percy-dom

Cargo.toml, crates/percy-dom/tests/testing_utilities.rs, crates/percy-preview-app/Cargo.toml, crates/percy-preview-app/src/app.rs, crates/percy-preview-app/src/app/config.rs, crates/percy-preview-app/src/app/world.rs, crates/percy-preview-app/src/app/world/message.rs, crates/percy-preview-app/src/app/world/message/message_handlers.rs, crates/percy-preview-app/src/app/world/message/message_handlers/set_route_data_provider_message_handler.rs, crates/percy-preview-app/src/app/world/resources.rs, crates/percy-preview-app/src/app/world/state.rs, crates/percy-preview-app/src/app/world/world_config.rs, crates/percy-preview-app/src/lib.rs, crates/percy-preview-app/src/render.rs, crates/percy-preview-app/src/routes.rs, crates/percy-preview-app/src/view.rs, crates/percy-preview-app/src/view/index_route.rs, crates/percy-preview-app/src/view/routes.rs, crates/percy-preview/Cargo.toml, crates/percy-preview/README.md, crates/percy-preview/src/lib.rs, crates/percy-router-macro/src/route_macro.rs, crates/percy-router/src/route.rs
This commit introduces the percy-preview and percy-preview-app crates.
These crates can be used to preview view components.
=> Introduce percy-preview

crates/percy-cli/Cargo.toml, crates/percy-cli/src/subcommand/preview.rs, crates/percy-preview-server/Cargo.toml, crates/percy-preview-server/src/config.rs, crates/percy-preview-server/src/filesystem_watcher.rs, crates/percy-preview-server/src/lib.rs, crates/percy-preview-server/src/router.rs, crates/percy-preview-server/src/router/websocket.rs, crates/percy-preview-server/src/websocket.rs, examples/component-preview/src/views/controls_header/controls_header_view.rs
This commit makes it so that the Percy Preview App refreshes whenever
the crate that is being previewed changes.
This helps your components live reload as you work.
We're quickly throwing some code together to feel out the experience.
=> Make Percy preview refresh on code change

crates/percy-preview-app/src/view/visualize_component_route.rs, crates/percy-preview-server/src/filesystem_watcher.rs, crates/percy-preview/src/lib.rs, examples/component-preview/src/views/login/login_form_view.rs
This commit adds a description to the `percy_preview::Preview` type.
This description gets rendered above the component preview.
=> Render preview description

crates/percy-dom/Cargo.toml, crates/percy-dom/src/lib.rs
This commit adds a `macro` feature to the percy-dom crate.
The feature can be used to enable/disable the `html-macro`
dependency.
We currently enable this feature by default. This was not a deeply
thought through decision. We're starting with it enabled
to preserve backwards compatibility.
=> Add `macro` feature to percy-dom

crates/percy-dom/src/diff.rs, crates/percy-dom/src/diff/diff_test_case.rs, crates/percy-dom/src/diff/longest_increasing_subsequence.rs, crates/percy-dom/src/single_page_app.rs, crates/percy-preview-app/build.rs
This commit make our diffing algorithm prefer to moving focusable
elements such as inputs and textareas over removing and recreating them.
This is meant to prevent scenarios where our diff/patch would lead to an
input element losing focus, such as when prepending a sibling element
before an input element.
For example, before this commit the following start and end virtual dom
would lead to us recreating the input element and so it would lose focus.
```
Start: <div> <input /> </div>
End: <div> <br /> <input /> </div>
```
As of this commit the input element will no longer lose focus.
We accomplish this by treating focusable elements such as inputs and
textareas in much the same way that we treat keyed elements, such that
the diffing algorithm attempts to, when possible, move them instead of …
=> Preserve focusable elements

crates/percy-dom/Cargo.toml, crates/percy-dom/src/diff.rs
Fix textarea implicit keying
This commit adds a test and fix for a bug where we were using `input`
element implicit keys for `textarea` elements.
=> Fix textarea implicit keying

crates/percy-dom/src/diff.rs
This commit introduces implicit keys to siblings that are being diffed.
This was introduced to solve for the following case:
```text
start: <div> <span><input /></span> </div>
end: <div> <img /> <span><input /></span> </div>
```
Before this commit, if the `input` in the above example was focused at
the start, it would lose its focused after the patches were applied
since the `span` would have gotten replaced by the `img`.
Now all elements with the same tag are implicitly keyed such that
the diffing algorithm will send up generating patches that will move
elements instead of replace them, when possible.
Note that there is a cost to this, since the longest increasing
subsequence algorithm that we're using to diff keyed siblings is
`O(n log n).
This commit makes it such that `n` will always …
=> Introduce implicit keying

crates/percy-dom/src/diff.rs, crates/percy-dom/src/patch/apply_patches.rs, crates/virtual-node/src/event/virtual_events.rs
This commit fixing the diffing bug where we were using the wrong node
index when moving siblings under certain conditions.
=> Fix indexing when moving nodes

crates/html-macro-test/src/tests/all_tests.rs, crates/html-macro/src/parser/open_tag.rs, crates/html-macro/src/parser/open_tag/event.rs, crates/html-macro/src/tag.rs, crates/percy-dom/tests/text.rs, crates/percy-router-macro-test/src/book_example.rs, crates/virtual-node/src/event/virtual_events.rs, examples/isomorphic/server/src/actix_server.rs
This commit makes it possible to use hyphenated attribute names when
creating elements using the `html!` macro.
For example, the following is now possible:
```rust
html! {
<svg
xmlns="http://www.w3.org/2000/svg"
stroke-width="1.5"
// ...
>
// ...
</svg>
}
```
Before this commit trying to add a "stroke-width" attribute would have
led to a compile time error.
=> `html!` macro support hyphens in attributes

crates/html-macro/src/tag.rs
This commit adds support for when a hyphenated attribute is the second
attribute.
```rust
html! {
<path
d="..."
stroke-linejoin="miter"
/>
}
```
Before this commit the `html!` procedural macro would error if a
hyphenated attribute was present and was not the first attribute.
=> Support hyphenated attribute as second

crates/percy-router/src/route.rs
This commit fixes the route matching logic when a static segment comes
after a dynamic segment.
For instance, before this commit the path "/5/bar" would match the route
definition `/:id/foo`.
This commit fixes that error.
=> Fix matching static after dynamic segment

crates/html-macro/src/parser/open_tag.rs, crates/virtual-node/src/velement/attribute_value.rs
This commit adds documentation that explains how `AttributeValue`'s
`From` implementation is used.
=> Document AttributeValue::from
